### ISSUE TITLE
Create participant agreement message

### ISSUE THREAD

**Issue by pglevy** [Bixal/methods#82]
[Example from 18F UX Guide](https://github.com/18F/ux-guide/blob/master/_pages/resources/email-templates/researcher-sends-agreement.md)

**Comment by katharine-carr** [comment]
Hello!

Here is this for review @pglevy and @sofya-UX :

### Guidance
* The goal of this communication is to provide the consent form and ask for a signature.
* There’s no need to include too many specifics in this message. Instead, keep it brief and high-level in the case any changes are made, you don’t have to update both the form and the message.
* Keep in mind that participants may be hesitant to download items or click links in messages from people they do not know because of security concerns. Account for this by allowing the participant to go through the consent form verbally during the session.

**Guidance for the Recruiting card:**
* Through our communications with participants, we should show that we thoughtful and trustworthy researchers. Communicating professionally will build their trust in us and lead to more open and honest feedback.

### Template (Attachment)
Hi [[[ Participant Name ]]],

We are looking forward to your participation in our research. Attached to this email is a participant agreement form that outlines what you need to know about our research. Could you review it, and if all looks good sign and send back before our session? I’m happy to answer any questions. If you are unable to fill out the form, we can go over it together at the beginning of the session.

Thanks,
[[[ Your Name ]]]

### Template (Link)
Hi [[[ Participant Name ]]],

We are looking forward to your participation in our research. [[[ This link ]]] takes you to a participant agreement form that outlines what you need to know about our research. Could you review it, and if all looks good fill it out before our session? I’m happy to answer any questions. If you are unable to fill out the form, we can go over it together at the beginning of the session.

Thanks,
[[[ Your Name ]]]

**Comment by sofya-UX** [comment]
@katharine-carr looks good. I went in and made minor edits (articles, some "are"-s), looking forward to seeing this published!

**Comment by sofya-UX** [comment]
... added "your study participant with" in the guidance section.

**Comment by pglevy** [comment]
Moving the latest version (with Sofya's) into markdown now. May make a few copyedits as well.

**Comment by pglevy** [comment]
Tightened up a few things. [Live here](https://bixal.github.io/methods/agreement-message/). Let me know if you have any additional feedback @Bixal/methods.

**Comment by sofya-UX** [comment]
@pglevy I just used this in the email to send you the link for the USWDS study consent form, embracing a total test mode here.
I removed the last sentence to see if it increases the conversion rate LOL.
